// Generated by gencpp from file slam_exploration_bot/FrontierList.msg
// DO NOT EDIT!


#ifndef SLAM_EXPLORATION_BOT_MESSAGE_FRONTIERLIST_H
#define SLAM_EXPLORATION_BOT_MESSAGE_FRONTIERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slam_exploration_bot/Frontier.h>

namespace slam_exploration_bot
{
template <class ContainerAllocator>
struct FrontierList_
{
  typedef FrontierList_<ContainerAllocator> Type;

  FrontierList_()
    : frontiers()  {
    }
  FrontierList_(const ContainerAllocator& _alloc)
    : frontiers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::slam_exploration_bot::Frontier_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::slam_exploration_bot::Frontier_<ContainerAllocator> >> _frontiers_type;
  _frontiers_type frontiers;





  typedef boost::shared_ptr< ::slam_exploration_bot::FrontierList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_exploration_bot::FrontierList_<ContainerAllocator> const> ConstPtr;

}; // struct FrontierList_

typedef ::slam_exploration_bot::FrontierList_<std::allocator<void> > FrontierList;

typedef boost::shared_ptr< ::slam_exploration_bot::FrontierList > FrontierListPtr;
typedef boost::shared_ptr< ::slam_exploration_bot::FrontierList const> FrontierListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_exploration_bot::FrontierList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_exploration_bot::FrontierList_<ContainerAllocator1> & lhs, const ::slam_exploration_bot::FrontierList_<ContainerAllocator2> & rhs)
{
  return lhs.frontiers == rhs.frontiers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_exploration_bot::FrontierList_<ContainerAllocator1> & lhs, const ::slam_exploration_bot::FrontierList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_exploration_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_exploration_bot::FrontierList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_exploration_bot::FrontierList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_exploration_bot::FrontierList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88ec557839bec196cc2b3b90ef57f3e8";
  }

  static const char* value(const ::slam_exploration_bot::FrontierList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88ec557839bec196ULL;
  static const uint64_t static_value2 = 0xcc2b3b90ef57f3e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_exploration_bot/FrontierList";
  }

  static const char* value(const ::slam_exploration_bot::FrontierList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_exploration_bot/Frontier[] frontiers\n"
"\n"
"================================================================================\n"
"MSG: slam_exploration_bot/Frontier\n"
"int32 size\n"
"geometry_msgs/Point centroid\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::slam_exploration_bot::FrontierList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontiers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontierList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_exploration_bot::FrontierList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_exploration_bot::FrontierList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "frontiers: ";
    if (v.frontiers.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.frontiers.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::slam_exploration_bot::Frontier_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.frontiers[i]);
    }
    if (v.frontiers.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_EXPLORATION_BOT_MESSAGE_FRONTIERLIST_H
